/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import static dbms.Main.BookingTab;
import static dbms.Main.holtab;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dell
 */
public class BookHolidays extends javax.swing.JFrame {

    /**
     * Creates new form BookHolidays
     */
    public BookHolidays() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        Tname3 = new javax.swing.JTextField();
        male1 = new javax.swing.JRadioButton();
        Female1 = new javax.swing.JRadioButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        passport3 = new javax.swing.JTextField();
        confirmbookbtn2 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        conblbl1 = new javax.swing.JTextArea();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 204));
        jLabel62.setText("Traveller Name:");
        jPanel6.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, -1));

        Tname3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tname3ActionPerformed(evt);
            }
        });
        jPanel6.add(Tname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 250, 30));

        bg.add(male1);
        male1.setText("Male");
        jPanel6.add(male1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        bg.add(Female1);
        Female1.setText("Female");
        jPanel6.add(Female1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel63.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 102));
        jLabel63.setText("Book a Holiday");
        jPanel6.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 14, 172, 21));

        jLabel64.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 204));
        jLabel64.setText("Gender:");
        jPanel6.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, -1));

        jLabel65.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 0, 204));
        jLabel65.setText("Identification Number:");
        jPanel6.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 140, -1, -1));

        passport3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel6.add(passport3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 30));

        confirmbookbtn2.setBackground(new java.awt.Color(0, 0, 102));
        confirmbookbtn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        confirmbookbtn2.setForeground(new java.awt.Color(255, 255, 255));
        confirmbookbtn2.setText("Confirm Booking");
        confirmbookbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbookbtn2ActionPerformed(evt);
            }
        });
        jPanel6.add(confirmbookbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 180, 30));

        jLabel66.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 204));
        jLabel66.setText("Details :");
        jPanel6.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 110, 17));

        jLabel67.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 204));
        jLabel67.setText("Price:");
        jPanel6.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 81, -1));

        price1.setBackground(new java.awt.Color(255, 255, 255));
        price1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel6.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 169, 25));

        conblbl1.setEditable(false);
        conblbl1.setColumns(20);
        conblbl1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        conblbl1.setRows(5);
        jScrollPane9.setViewportView(conblbl1);

        jPanel6.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 251, -1));

        cancel.setBackground(new java.awt.Color(0, 0, 102));
        cancel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel6.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 150, -1));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 2, 14)); // NOI18N
        jLabel1.setText("Identification Number can be aadhar number, ");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 280, -1));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 2, 14)); // NOI18N
        jLabel3.setText("Passport number or any other valid identity proof");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 290, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/WorldTravelMapAmericasph.jpg"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbookbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbookbtn2ActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        int number=0;
        String modifiedDate= new SimpleDateFormat("dd-MM-yyyy").format(date);
        String da=String.valueOf(modifiedDate);
        String g;
        if((Tname3.getText()!=null)&&(passport3.getText()!=null)&&(bg.getSelection()!=null) ){
           if(male1.isSelected())
               g="M"; 
            
            else
                g="F";
           String td="IDNo="+passport3.getText()+" "+"G="+g;
           int dialog=JOptionPane.showConfirmDialog(null, "Confirm your Booking?");
            if(dialog==JOptionPane.YES_OPTION){
                try{
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                String query="insert into booking(traveller_name,username,booking_date,traveller_details,hid,BOOKING__DETAILS) values(?,?,?,?,?,?)";
                PreparedStatement stat=con.prepareStatement(query);
                stat.setString(1,Tname3.getText());
                stat.setString(2,Login.n);
                stat.setString(3,da);
                stat.setString(4,td);
                stat.setString(5,Main.hid);
                 stat.setString(6,conblbl1.getText());
                ResultSet res=stat.executeQuery();
                JOptionPane.showMessageDialog(null,"Booking Done!");
                String query8="select BOOKINGID,traveller_name,booking_date,traveller_details,hid,hotel_id,BOOKING__DETAILS from Booking where username=?";
                PreparedStatement stat8=con.prepareStatement(query8);
                stat8.setString(1,Login.n);
                ResultSet res8=stat8.executeQuery();
                BookingTab.setModel(DbUtils.resultSetToTableModel(res8));
                String query2 = "{call PROC()}"; 
                CallableStatement statement = con.prepareCall(query2);   
                statement.execute(); 
                con.close();
                }
                catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null,"Class not found ");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Invalid Input");
                }
            }
            int d=JOptionPane.showConfirmDialog(null, "Add Another Traveler?");
                if(d==JOptionPane.NO_OPTION){
                    
                    try {
                        Class.forName("oracle.jdbc.OracleDriver");
                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                        String query="Select destination,source,date_of_travel,duration,price,details,agency_name,NUMBER_OF_PACKAGES from travel_agency a,holiday b where a.tid=b.tid";
                        PreparedStatement stat=con.prepareStatement(query);
                        ResultSet res=stat.executeQuery();
                        holtab.setModel(DbUtils.resultSetToTableModel(res));
                        con.close();
                    }
                    
                    catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null,"Class not found ");
                    } catch (SQLException ex) {
                         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.dispose();
                }
                else if(d==JOptionPane.YES_OPTION){
                        try{
                        Class.forName("oracle.jdbc.OracleDriver");
                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                        String query1="select * from holiday where hid=?";
                        PreparedStatement stat1=con.prepareStatement(query1);
                        stat1.setString(1,Main.hid);
                        ResultSet res1=stat1.executeQuery();
                        if(res1.next()){
                            Tname3.setText(null);
                            passport3.setText(null);
                            bg.clearSelection();
                        }
                        else{
                           JOptionPane.showMessageDialog(null,"All Packages are Booked . Sorry! "); 
                            try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                            String query="Select destination,source,date_of_travel,duration,price,details,agency_name,NUMBER_OF_PACKAGES from travel_agency a,holiday b where a.tid=b.tid";
                            PreparedStatement stat=con2.prepareStatement(query);
                            ResultSet res=stat.executeQuery();
                            holtab.setModel(DbUtils.resultSetToTableModel(res));
                            con.close();
                    }
                    
                    catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null,"Class not found ");
                    } catch (SQLException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.dispose();
                        }
                        }
                        catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null,"Class not found ");
                        } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null,"Invalid Input");
                    }
                }
        }
        else{
            JOptionPane.showMessageDialog(null, "Fields are empty");
        }
    }//GEN-LAST:event_confirmbookbtn2ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conblbl1.setText("Destination- "+Main.dst+"\n"+"From- "+Main.source+"\n"+"Date of travel- "+Main.dot+"\n"+"Duration- "+Main.duration+"\n"+"Details- "+Main.details+"\n");
        price1.setText(Main.holprice);
    }//GEN-LAST:event_formWindowOpened

    private void Tname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tname3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookHolidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookHolidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookHolidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookHolidays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookHolidays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton Female1;
    private javax.swing.JTextField Tname3;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton cancel;
    private javax.swing.JTextArea conblbl1;
    private javax.swing.JButton confirmbookbtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    public static javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JRadioButton male1;
    private javax.swing.JTextField passport3;
    private javax.swing.JLabel price1;
    // End of variables declaration//GEN-END:variables
}
