/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import static dbms.Login.n;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.font.TextAttribute;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dell
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
     Font original;
     public static String dst,source,dot,duration,details,holprice,hid;
     public static String Hotelname,Guests,City,Description,N,hotprice,hotelid,bed;
    public Main() {
        initComponents();
        ckin.setMinSelectableDate(new Date());
        ckout.setMinSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        bg3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Bookings = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingTab = new javax.swing.JTable();
        cancelbook = new java.awt.Button();
        jToolBar1 = new javax.swing.JToolBar();
        Logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Holidays = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        Logout1 = new javax.swing.JLabel();
        gif = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        woeksc = new javax.swing.JLabel();
        holiday = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        dest = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        bud = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        holtab = new javax.swing.JTable();
        BookHoliday = new java.awt.Button();
        jLabel48 = new javax.swing.JLabel();
        holok = new java.awt.Button();
        from = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        viewallhol = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TravelAgencies = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        Logout2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tacity = new javax.swing.JTextField();
        tastate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        GO = new java.awt.Button();
        packfromTA = new javax.swing.JLabel();
        TAtabP = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAtable = new javax.swing.JTable();
        TAspecific = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        holtab1 = new javax.swing.JTable();
        BookBtnTA = new java.awt.Button();
        search = new javax.swing.JButton();
        viewallta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Hotels = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        Logout3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        GOHotel = new java.awt.Button();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        hottab = new javax.swing.JTable();
        BookHotelBtn = new java.awt.Button();
        ckin = new com.toedter.calendar.JDateChooser();
        ckout = new com.toedter.calendar.JDateChooser();
        viewallhot = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Account = new javax.swing.JPanel();
        jToolBar7 = new javax.swing.JToolBar();
        Logout6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Changepass = new javax.swing.JLabel();
        changep = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        confirmjButton1 = new javax.swing.JButton();
        oldpass = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        lbl6 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        jLabel56 = new javax.swing.JLabel();
        feedback = new javax.swing.JLabel();
        changep1 = new javax.swing.JPanel();
        lbl5 = new javax.swing.JLabel();
        Okfeedback = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        f1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 153));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(750, 470));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(750, 470));
        jTabbedPane1.setName("Account"); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(750, 470));

        Bookings.setBackground(new java.awt.Color(255, 255, 255));
        Bookings.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Bookings.setMaximumSize(new java.awt.Dimension(750, 470));
        Bookings.setPreferredSize(new java.awt.Dimension(750, 470));
        Bookings.setLayout(null);

        BookingTab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BookingTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(201), "2 Aug,2018", "Bengaluru", "Mangalore", "Nasil Saniah"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Date", "To", "From", "Passenger Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BookingTab.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BookingTab.setGridColor(new java.awt.Color(51, 51, 255));
        BookingTab.setRowHeight(30);
        jScrollPane1.setViewportView(BookingTab);

        Bookings.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 1090, 410);

        cancelbook.setActionCommand("Login");
        cancelbook.setBackground(new java.awt.Color(0, 0, 102));
        cancelbook.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancelbook.setForeground(new java.awt.Color(255, 255, 255));
        cancelbook.setLabel("Cancel Booking");
        cancelbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbookActionPerformed(evt);
            }
        });
        Bookings.add(cancelbook);
        cancelbook.setBounds(470, 620, 290, 40);

        jToolBar1.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar1.setRollover(true);

        Logout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        jToolBar1.add(Logout);

        Bookings.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1151, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images.png"))); // NOI18N
        Bookings.add(jLabel1);
        jLabel1.setBounds(990, 60, 100, 83);

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Travart");
        Bookings.add(jLabel2);
        jLabel2.setBounds(1000, 150, 69, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/imgonline-com-ua-resize-oGMalFMqdp.png"))); // NOI18N
        Bookings.add(jLabel4);
        jLabel4.setBounds(0, 40, 1150, 720);

        jTabbedPane1.addTab("Bookings ", new javax.swing.ImageIcon(getClass().getResource("/dbms/book.png")), Bookings); // NOI18N

        Holidays.setBackground(new java.awt.Color(255, 255, 255));
        Holidays.setLayout(null);

        jToolBar2.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar2.setRollover(true);

        Logout1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Logout1.setText("Logout");
        Logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout1MouseExited(evt);
            }
        });
        jToolBar2.add(Logout1);

        Holidays.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 1151, 38);

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/ezgif.com-resize.gif"))); // NOI18N
        Holidays.add(gif);
        gif.setBounds(30, 90, 200, 200);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images.png"))); // NOI18N
        Holidays.add(logo);
        logo.setBounds(970, 50, 100, 83);

        name.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 102));
        name.setText("Travart");
        Holidays.add(name);
        name.setBounds(990, 140, 69, 29);

        woeksc.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        woeksc.setText("Tired of same work schedule? ");
        Holidays.add(woeksc);
        woeksc.setBounds(440, 80, 295, 29);

        holiday.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        holiday.setForeground(new java.awt.Color(51, 0, 102));
        holiday.setText("Book exotic Holiday getaways at amazing prices!!");
        Holidays.add(holiday);
        holiday.setBounds(320, 140, 500, 29);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 102));
        jLabel45.setText("Destination:");
        Holidays.add(jLabel45);
        jLabel45.setBounds(240, 190, 120, 32);
        Holidays.add(dest);
        dest.setBounds(380, 190, 148, 32);

        jLabel46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 102));
        jLabel46.setText("Budget:");
        Holidays.add(jLabel46);
        jLabel46.setBounds(550, 190, 90, 32);
        Holidays.add(bud);
        bud.setBounds(660, 190, 148, 33);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204,100));

        holtab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        holtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Dubai", "Mangalore", "3 Days", "50000"},
                {"Bali", "Delhi", "5 Days", "62000"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Destination", "From", "Duration", "Price"
            }
        ));
        holtab.setAlignmentX(2.0F);
        holtab.setAlignmentY(2.0F);
        holtab.setRowHeight(30);
        jScrollPane5.setViewportView(holtab);

        BookHoliday.setActionCommand("Login");
        BookHoliday.setBackground(new java.awt.Color(0, 0, 102));
        BookHoliday.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BookHoliday.setForeground(new java.awt.Color(255, 255, 255));
        BookHoliday.setLabel("Book");
        BookHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookHolidayActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 102));
        jLabel48.setText("Select the Package You want to book...");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(398, 398, 398)
                                .addComponent(BookHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel48)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setVisible(false);

        Holidays.add(jPanel8);
        jPanel8.setBounds(19, 328, 1122, 350);

        holok.setActionCommand("Add");
        holok.setBackground(new java.awt.Color(0, 0, 102));
        holok.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        holok.setForeground(new java.awt.Color(255, 255, 255));
        holok.setLabel("OK");
        holok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holokActionPerformed(evt);
            }
        });
        Holidays.add(holok);
        holok.setBounds(670, 250, 289, 37);
        Holidays.add(from);
        from.setBounds(380, 230, 148, 33);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 102));
        jLabel47.setText("From:");
        Holidays.add(jLabel47);
        jLabel47.setBounds(250, 240, 70, 32);

        viewallhol.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        viewallhol.setForeground(new java.awt.Color(51, 0, 102));
        viewallhol.setText("View all available Holiday Packages");
        viewallhol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewallholMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewallholMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewallholMouseExited(evt);
            }
        });
        Holidays.add(viewallhol);
        viewallhol.setBounds(70, 290, 371, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/imgonline-com-ua-resize-oGMalFMqdp.png"))); // NOI18N
        Holidays.add(jLabel5);
        jLabel5.setBounds(0, 40, 1150, 720);

        jTabbedPane1.addTab("Holidays", new javax.swing.ImageIcon(getClass().getResource("/dbms/holiday.png")), Holidays); // NOI18N

        TravelAgencies.setBackground(new java.awt.Color(255, 255, 255));
        TravelAgencies.setLayout(null);

        jToolBar3.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar3.setRollover(true);

        Logout2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Logout2.setText("Logout");
        Logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout2MouseExited(evt);
            }
        });
        jToolBar3.add(Logout2);

        TravelAgencies.add(jToolBar3);
        jToolBar3.setBounds(0, 0, 1151, 38);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images.png"))); // NOI18N
        TravelAgencies.add(jLabel7);
        jLabel7.setBounds(1032, 44, 100, 83);

        jLabel8.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Travart");
        TravelAgencies.add(jLabel8);
        jLabel8.setBounds(1049, 137, 69, 29);

        tacity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tacity.setForeground(new java.awt.Color(102, 102, 102));
        tacity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tacity.setText("City");
        tacity.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tacity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tacityMouseClicked(evt);
            }
        });
        tacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacityActionPerformed(evt);
            }
        });
        TravelAgencies.add(tacity);
        tacity.setBounds(80, 200, 193, 30);

        tastate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tastate.setForeground(new java.awt.Color(102, 102, 102));
        tastate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tastate.setText("State");
        tastate.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tastate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tastateMouseClicked(evt);
            }
        });
        tastate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tastateActionPerformed(evt);
            }
        });
        TravelAgencies.add(tastate);
        tastate.setBounds(330, 200, 193, 30);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel3.setText("Need Help? Find the nerest Travel agency!!");
        TravelAgencies.add(jLabel3);
        jLabel3.setBounds(350, 140, 580, 33);

        GO.setActionCommand("Login");
        GO.setBackground(new java.awt.Color(51, 102, 255));
        GO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        GO.setForeground(new java.awt.Color(255, 255, 255));
        GO.setLabel("GO");
        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });
        TravelAgencies.add(GO);
        GO.setBounds(200, 250, 163, 37);

        packfromTA.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        packfromTA.setForeground(new java.awt.Color(51, 0, 153));
        packfromTA.setText("Need packages from the travel agency near you? Click here!");
        packfromTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packfromTAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                packfromTAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                packfromTAMouseExited(evt);
            }
        });
        TravelAgencies.add(packfromTA);
        packfromTA.setBounds(10, 580, 640, 33);

        TAtabP.setBackground(new java.awt.Color(255, 255, 255,100));

        TAtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Agency Name", "Area", "City", "State", "Phone No"
            }
        ));
        TAtable.setRowHeight(30);
        jScrollPane2.setViewportView(TAtable);

        javax.swing.GroupLayout TAtabPLayout = new javax.swing.GroupLayout(TAtabP);
        TAtabP.setLayout(TAtabPLayout);
        TAtabPLayout.setHorizontalGroup(
            TAtabPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAtabPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        TAtabPLayout.setVerticalGroup(
            TAtabPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TAtabPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        TAtabP.setVisible(false);

        TravelAgencies.add(TAtabP);
        TAtabP.setBounds(10, 340, 550, 199);

        TAspecific.setBackground(new java.awt.Color(255, 255, 255,100));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 153));
        jLabel55.setText("Enter Travel Agency Name:");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        holtab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Destination", "From", "Duration", "Price"
            }
        ));
        holtab1.setAlignmentX(2.0F);
        holtab1.setAlignmentY(2.0F);
        holtab1.setRowHeight(30);
        jScrollPane7.setViewportView(holtab1);

        BookBtnTA.setActionCommand("Login");
        BookBtnTA.setBackground(new java.awt.Color(0, 0, 102));
        BookBtnTA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BookBtnTA.setForeground(new java.awt.Color(255, 255, 255));
        BookBtnTA.setLabel("Book");
        BookBtnTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBtnTAActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 102, 255));
        search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TAspecificLayout = new javax.swing.GroupLayout(TAspecific);
        TAspecific.setLayout(TAspecificLayout);
        TAspecificLayout.setHorizontalGroup(
            TAspecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAspecificLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TAspecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TAspecificLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TAspecificLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
            .addGroup(TAspecificLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(BookBtnTA, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TAspecificLayout.setVerticalGroup(
            TAspecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAspecificLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(TAspecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BookBtnTA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        TravelAgencies.add(TAspecific);
        TAspecific.setBounds(567, 210, 570, 365);
        TAspecific.setVisible(false);

        viewallta.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        viewallta.setForeground(new java.awt.Color(0, 0, 153));
        viewallta.setText("View all the Travel Agencies");
        viewallta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewalltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewalltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewalltaMouseExited(evt);
            }
        });
        TravelAgencies.add(viewallta);
        viewallta.setBounds(90, 300, 277, 29);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/imgonline-com-ua-resize-oGMalFMqdp.png"))); // NOI18N
        TravelAgencies.add(jLabel11);
        jLabel11.setBounds(0, 50, 1150, 720);

        jTabbedPane1.addTab("Travel Agencies", new javax.swing.ImageIcon(getClass().getResource("/dbms/ta.png")), TravelAgencies); // NOI18N

        Hotels.setBackground(new java.awt.Color(255, 255, 255));
        Hotels.setLayout(null);

        jToolBar4.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar4.setRollover(true);

        Logout3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Logout3.setText("Logout");
        Logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout3MouseExited(evt);
            }
        });
        jToolBar4.add(Logout3);

        Hotels.add(jToolBar4);
        jToolBar4.setBounds(0, 0, 1151, 38);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images.png"))); // NOI18N
        Hotels.add(jLabel9);
        jLabel9.setBounds(980, 70, 100, 83);

        jLabel10.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Travart");
        Hotels.add(jLabel10);
        jLabel10.setBounds(1000, 160, 69, 29);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("City");
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        Hotels.add(jTextField7);
        jTextField7.setBounds(500, 140, 213, 30);

        jLabel57.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(51, 51, 51));
        jLabel57.setText("Book Hotels at the the Best price");
        Hotels.add(jLabel57);
        jLabel57.setBounds(400, 100, 440, 33);

        GOHotel.setActionCommand("Login");
        GOHotel.setBackground(new java.awt.Color(51, 102, 255));
        GOHotel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GOHotel.setForeground(new java.awt.Color(255, 255, 255));
        GOHotel.setLabel("GO");
        GOHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOHotelActionPerformed(evt);
            }
        });
        Hotels.add(GOHotel);
        GOHotel.setBounds(510, 230, 163, 37);

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 102));
        jLabel59.setText("Check-OUT");
        Hotels.add(jLabel59);
        jLabel59.setBounds(610, 190, 100, 17);

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 102));
        jLabel60.setText("Check-IN");
        Hotels.add(jLabel60);
        jLabel60.setBounds(350, 190, 80, 17);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255,100));

        hottab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Prince Garddenia", "Yes", "Pool table,Complimentry Breakfast", "2000"},
                {"Madhuvan", "No", "Veg Food, Play Area", "1500"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hotel Name", "Availability", "Features", "Room Cost/Day"
            }
        ));
        hottab.setRowHeight(30);
        jScrollPane8.setViewportView(hottab);

        BookHotelBtn.setActionCommand("Login");
        BookHotelBtn.setBackground(new java.awt.Color(0, 0, 102));
        BookHotelBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BookHotelBtn.setForeground(new java.awt.Color(255, 255, 255));
        BookHotelBtn.setLabel("Book");
        BookHotelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookHotelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(BookHotelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(481, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(BookHotelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Hotels.add(jPanel7);
        jPanel7.setBounds(20, 330, 1121, 287);
        jPanel7.setVisible(false);
        Hotels.add(ckin);
        ckin.setBounds(440, 180, 130, 30);
        Hotels.add(ckout);
        ckout.setBounds(720, 180, 130, 30);

        viewallhot.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        viewallhot.setForeground(new java.awt.Color(0, 0, 153));
        viewallhot.setText("View all the available Hotels");
        viewallhot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewallhotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewallhotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewallhotMouseExited(evt);
            }
        });
        Hotels.add(viewallhot);
        viewallhot.setBounds(240, 290, 286, 29);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/imgonline-com-ua-resize-oGMalFMqdp.png"))); // NOI18N
        Hotels.add(jLabel12);
        jLabel12.setBounds(0, 40, 1140, 720);

        jTabbedPane1.addTab("Hotels", new javax.swing.ImageIcon(getClass().getResource("/dbms/hotel.png")), Hotels); // NOI18N

        Account.setBackground(new java.awt.Color(255, 255, 255));
        Account.setLayout(null);

        jToolBar7.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar7.setRollover(true);

        Logout6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Logout6.setText("Logout");
        Logout6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout6MouseExited(evt);
            }
        });
        jToolBar7.add(Logout6);

        Account.add(jToolBar7);
        jToolBar7.setBounds(0, 0, 1151, 38);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images.png"))); // NOI18N
        Account.add(jLabel15);
        jLabel15.setBounds(988, 44, 100, 83);

        jLabel16.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Travart");
        Account.add(jLabel16);
        jLabel16.setBounds(1011, 138, 69, 29);

        Changepass.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        Changepass.setForeground(new java.awt.Color(255, 255, 255));
        Changepass.setText("--Change Password");
        Changepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangepassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangepassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangepassMouseExited(evt);
            }
        });
        Account.add(Changepass);
        Changepass.setBounds(20, 170, 250, 25);

        changep.setBackground(new java.awt.Color(39, 55, 70,190));
        changep.setForeground(new java.awt.Color(51, 0, 153));

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Old-Password");

        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("Re-Password");

        confirmjButton1.setBackground(new java.awt.Color(0, 102, 255));
        confirmjButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        confirmjButton1.setForeground(new java.awt.Color(255, 255, 255));
        confirmjButton1.setText("Confirm");
        confirmjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButton1ActionPerformed(evt);
            }
        });

        lbl6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("New-Password");

        javax.swing.GroupLayout changepLayout = new javax.swing.GroupLayout(changep);
        changep.setLayout(changepLayout);
        changepLayout.setHorizontalGroup(
            changepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changepLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(changepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2)
                    .addComponent(lbl1)
                    .addComponent(lbl6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(changepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(changepLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(confirmjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        changepLayout.setVerticalGroup(
            changepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changepLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(changepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(changepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(changepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(confirmjButton1)
                .addGap(19, 19, 19))
        );

        Account.add(changep);
        changep.setBounds(70, 420, 370, 280);
        changep.setVisible(false);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/giphy (1).gif"))); // NOI18N
        Account.add(jLabel56);
        jLabel56.setBounds(306, 66, 500, 281);

        feedback.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        feedback.setForeground(new java.awt.Color(255, 255, 255));
        feedback.setText("--Give Feedback");
        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feedbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feedbackMouseExited(evt);
            }
        });
        Account.add(feedback);
        feedback.setBounds(20, 230, 230, 25);

        changep1.setBackground(new java.awt.Color(39, 55, 70,190));

        lbl5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("Give Feedback");

        Okfeedback.setBackground(new java.awt.Color(0, 102, 255));
        Okfeedback.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Okfeedback.setForeground(new java.awt.Color(255, 255, 255));
        Okfeedback.setText("OK");
        Okfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkfeedbackActionPerformed(evt);
            }
        });

        f1.setColumns(20);
        f1.setRows(5);
        jScrollPane6.setViewportView(f1);

        javax.swing.GroupLayout changep1Layout = new javax.swing.GroupLayout(changep1);
        changep1.setLayout(changep1Layout);
        changep1Layout.setHorizontalGroup(
            changep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changep1Layout.createSequentialGroup()
                .addGroup(changep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changep1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changep1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(Okfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        changep1Layout.setVerticalGroup(
            changep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changep1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lbl5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(changep1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Okfeedback)
                .addGap(32, 32, 32))
        );

        Account.add(changep1);
        changep1.setBounds(500, 420, 410, 280);
        changep1.setVisible(false);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/abstract-astro-astronomy-956999.jpg"))); // NOI18N
        Account.add(jLabel13);
        jLabel13.setBounds(0, 40, 1150, 730);

        jTabbedPane1.addTab("Account", new javax.swing.ImageIcon(getClass().getResource("/dbms/My-Account-Icon.jpg")), Account); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Account");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OkfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkfeedbackActionPerformed
        // TODO add your handling code here:
            String u=f1.getText();
            try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="insert into feedback values(?,?)";
            PreparedStatement stat=con.prepareStatement(query);
            stat.setString(1,u);
            stat.setString(2,Login.n);
            int res=stat.executeUpdate();
            if(res==1){
           
               JOptionPane.showMessageDialog(null,"Feedback Submitted"); 
               f1.setText(null);
            }
          
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_OkfeedbackActionPerformed

    private void feedbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_feedbackMouseExited

    private void feedbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_feedbackMouseEntered

    private void feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseClicked
        // TODO add your handling code here:
        changep1.setVisible(true);
    }//GEN-LAST:event_feedbackMouseClicked

    private void confirmjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButton1ActionPerformed
        // TODO add your handling code here:
        String n1=Login.n;
        String p=oldpass.getText();
        String u=p1.getText();
        try {
            // TODO add your handling code here:
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="select * from users where username=? and password=?";
            PreparedStatement stat=con.prepareStatement(query);
            stat.setString(1,n1);
            stat.setString(2,p);
            ResultSet res=stat.executeQuery();
            if(res.next()){
                if(p1.getText().equals(p2.getText())){
                    
                    try {
                        
                        Class.forName("oracle.jdbc.OracleDriver");
                        Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                        String query2="update users set password=? where username=?";
                        PreparedStatement stat2=con2.prepareStatement(query2);
                        stat2.setString(1,u);
                        stat2.setString(2,n1);
                        int res2=stat2.executeUpdate();
                        if(res2==1){

                            JOptionPane.showMessageDialog(null,"Password changed successfully");

                        }
                        p1.setText(null);
                        oldpass.setText(null);
                        p2.setText(null);
                        con2.close();
                        con.close();
                    }
                    catch (SQLException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"New Passwords dont match");
                     p1.setText(null);
                        oldpass.setText(null);
                        p2.setText(null);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Incorrect Password");
                 p1.setText(null);
                        oldpass.setText(null);
                        p2.setText(null);
            }
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_confirmjButton1ActionPerformed

    private void ChangepassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangepassMouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_ChangepassMouseExited

    private void ChangepassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangepassMouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_ChangepassMouseEntered

    private void ChangepassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangepassMouseClicked
        // TODO add your handling code here:
        changep.setVisible(true);
    }//GEN-LAST:event_ChangepassMouseClicked

    private void Logout6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout6MouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_Logout6MouseExited

    private void Logout6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout6MouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_Logout6MouseEntered

    private void Logout6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout6MouseClicked
        // TODO add your handling code here:
        Login h=new Login();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout6MouseClicked

    private void BookHotelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookHotelBtnActionPerformed
        // TODO add your handling code here:
        if(hottab.getSelectedRow()!=-1){
            int i=hottab.getSelectedRow();
            Hotelname=(String) hottab.getValueAt(i,0);
            BigDecimal g=(BigDecimal)hottab.getValueAt(i, 4);
            Guests=String.valueOf(g);
            City=(String) hottab.getValueAt(i,6);
            Description=(String) hottab.getValueAt(i, 5);
            BigDecimal p= (BigDecimal) hottab.getValueAt(i,2);
            hotprice=String.valueOf(p);
            BigDecimal bb=(BigDecimal)hottab.getValueAt(i,3);
            bed=String.valueOf(bb);
            try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                String query="select hotel_id from hotel where hotel_name=? and city=? ";
                PreparedStatement stat=con.prepareStatement(query);
                stat.setString(1,Hotelname);
                stat.setString(2,City);
                ResultSet res=stat.executeQuery();
                if(res.next()){
                    hotelid=res.getString("hotel_id");
                    BookHotel h= new BookHotel();
                    h.setVisible(true);
                }
            }
            catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class not found ");
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Invalid Input");
            }
            
        }
        else
        JOptionPane.showMessageDialog(null,"No Hotel Selected");
         
    }//GEN-LAST:event_BookHotelBtnActionPerformed

    private void GOHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOHotelActionPerformed
        // TODO add your handling code here:
        
       if( !ckin.getDate().equals(null) && !ckout.getDate().equals(null)){
           jPanel7.setVisible(true);
           try {
            String c=jTextField7.getText();
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="Select hotel_name,available_rooms,price_perday,extra_bed_price,number_of_adults_in_room,DESCRIPTION,city from hotel where city=? and available_rooms>0 ";
            PreparedStatement stat=con.prepareStatement(query);
            stat.setString(1,c);
            ResultSet res=stat.executeQuery();
            hottab.setModel(DbUtils.resultSetToTableModel(res)); 
//            jTextField7.setText(null);
//            ckin.setDate(null);
//            ckout.setDate(null);
            con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class not found ");
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Sorry no hotels in this city!!") ;
        }
       }
        
    }//GEN-LAST:event_GOHotelActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void Logout3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout3MouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_Logout3MouseExited

    private void Logout3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout3MouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_Logout3MouseEntered

    private void Logout3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout3MouseClicked
        // TODO add your handling code here:
        Login h=new Login();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout3MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String p=jTextField6.getText();
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="Select destination,source,date_of_travel,duration,price,details from holiday b where tid in(select tid from travel_agency where agency_name=?)";
            PreparedStatement stat=con.prepareStatement(query);
            stat.setString(1,p);
            ResultSet res=stat.executeQuery();
            holtab1.setModel(DbUtils.resultSetToTableModel(res));
//            jTextField6.setText(null);
            con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class not found ");
        } catch (SQLException ex) {
           Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void BookBtnTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBtnTAActionPerformed
        // TODO add your handling code here:
        if(holtab1.getSelectedRow()!=-1){
            int i=holtab1.getSelectedRow();
            dst=(String) holtab1.getValueAt(i,0);
            source=(String) holtab1.getValueAt(i,1);
            dot=(String) holtab1.getValueAt(i,2);
            duration=(String) holtab1.getValueAt(i,3);
            details=(String) holtab1.getValueAt(i, 5);
            BigDecimal p= (BigDecimal) holtab1.getValueAt(i,4);
            holprice=String.valueOf(p);
            String name =(String) holtab1.getValueAt(i,6);
            try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                String query="select hid from holiday where destination=? and source=? and tid in(select tid from travel_agency where agency_name=?)";
                PreparedStatement stat=con.prepareStatement(query);
                stat.setString(1,dst);
                stat.setString(2,source);
                stat.setString(3,name);
                ResultSet res=stat.executeQuery();
                if(res.next()){
                    hid=res.getString("hid");
                }

            }
            catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class not found ");
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Invalid Input");
            }
            BookHolidays h= new BookHolidays();
            h.setVisible(true);
        }
        else
        JOptionPane.showMessageDialog(null,"No Package Selected");
    }//GEN-LAST:event_BookBtnTAActionPerformed

    private void packfromTAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packfromTAMouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_packfromTAMouseExited

    private void packfromTAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packfromTAMouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_packfromTAMouseEntered

    private void packfromTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packfromTAMouseClicked
        // TODO add your handling code here:
        TAspecific.setVisible(true);
    }//GEN-LAST:event_packfromTAMouseClicked

    private void GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOActionPerformed
        // TODO add your handling code here:
        if(tacity.getText().equals(null) && tastate.getText().equals(null)){
            JOptionPane.showMessageDialog(null,"City or State not entered");
        }
        else{
            TAtabP.setVisible(true);
            String city=tacity.getText();
            String S=tastate.getText();
            try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                String query="Select agency_name,area,city,state,phone_no from travel_agency where city=? and state=?";
                PreparedStatement stat=con.prepareStatement(query);
                stat.setString(1,city);
                stat.setString(2,S);
                ResultSet res=stat.executeQuery();
                TAtable.setModel(DbUtils.resultSetToTableModel(res));
//                tacity.setText("City");
//                tastate.setText("State");
                con.close();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class not found ");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Invalid Input");
            }
        }

    }//GEN-LAST:event_GOActionPerformed

    private void tastateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tastateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tastateActionPerformed

    private void tastateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tastateMouseClicked
        // TODO add your handling code here:
        tastate.setText(null);
    }//GEN-LAST:event_tastateMouseClicked

    private void tacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tacityActionPerformed

    private void tacityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tacityMouseClicked
        // TODO add your handling code here:
        tacity.setText(null);
    }//GEN-LAST:event_tacityMouseClicked

    private void Logout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout2MouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_Logout2MouseExited

    private void Logout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout2MouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_Logout2MouseEntered

    private void Logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout2MouseClicked
        // TODO add your handling code here:
        Login h=new Login();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout2MouseClicked

    private void viewallholMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallholMouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_viewallholMouseExited

    private void viewallholMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallholMouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_viewallholMouseEntered

    private void viewallholMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallholMouseClicked
        // TODO add your handling code here:
        jPanel8.setVisible(true);
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="Select destination,source,date_of_travel,duration,price,details,agency_name,NUMBER_OF_PACKAGES from travel_agency a,holiday b where a.tid=b.tid";
            PreparedStatement stat=con.prepareStatement(query);
            ResultSet res=stat.executeQuery();
            holtab.setModel(DbUtils.resultSetToTableModel(res));
            con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class not found ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Invalid Input");
        }
    }//GEN-LAST:event_viewallholMouseClicked

    private void holokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holokActionPerformed
        // TODO add your handling code here:
        jPanel8.setVisible(true);
        String Dest=dest.getText();
        String B=bud.getText();
        String From=from.getText();
        if(Dest.equals(null)|| B.equals(null)|| From.equals(null)){
            JOptionPane.showMessageDialog(null," Input");
        }
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="Select destination,source,date_of_travel,duration,price,details,agency_name from travel_agency a,holiday b where a.tid=b.tid and destination=? and source=? and price<=? and NUMBER_OF_PACKAGES>0";
            PreparedStatement stat=con.prepareStatement(query);
            stat.setString(1,Dest);
            stat.setString(2,From);
            stat.setString(3,B);
            ResultSet res=stat.executeQuery();
            holtab.setModel(DbUtils.resultSetToTableModel(res));
//            dest.setText(null);
//            bud.setText(null);
//            from.setText(null);
            con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class not found ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Invalid Input");
        }

    }//GEN-LAST:event_holokActionPerformed

    private void BookHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookHolidayActionPerformed
        // TODO add your handling code here:

        if(holtab.getSelectedRow()!=-1){
            int i=holtab.getSelectedRow();
            dst=(String) holtab.getValueAt(i,0);
            source=(String) holtab.getValueAt(i,1);
            dot=(String) holtab.getValueAt(i,2);
            duration=(String) holtab.getValueAt(i,3);
            details=(String) holtab.getValueAt(i, 5);
            BigDecimal p= (BigDecimal) holtab.getValueAt(i,4);
            holprice=String.valueOf(p);
            String name =(String) holtab.getValueAt(i,6);
            try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                String query="select hid from holiday where destination=? and source=? and tid in(select tid from travel_agency where agency_name=?)";
                PreparedStatement stat=con.prepareStatement(query);
                stat.setString(1,dst);
                stat.setString(2,source);
                stat.setString(3,name);
                ResultSet res=stat.executeQuery();
                if(res.next()){
                    hid=res.getString("hid");
                }

            }
            catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class not found ");
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Invalid Input");
            }
            BookHolidays h= new BookHolidays();
            h.setVisible(true);
        }
        else
        JOptionPane.showMessageDialog(null,"No Package Selected");
    }//GEN-LAST:event_BookHolidayActionPerformed

    private void Logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_Logout1MouseExited

    private void Logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_Logout1MouseEntered

    private void Logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseClicked
        // TODO add your handling code here:
        Login h=new Login();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout1MouseClicked

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        Login h=new Login();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
        jTextField7.setText(null);
    }//GEN-LAST:event_jTextField7MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="select BOOKINGID,traveller_name,booking_date,traveller_details,hid,hotel_id,BOOKING__DETAILS from Booking where username=?";
            PreparedStatement stat=con.prepareStatement(query);
            stat.setString(1,Login.n);
            ResultSet res=stat.executeQuery();
           BookingTab.setModel(DbUtils.resultSetToTableModel(res));
         
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void viewallhotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallhotMouseClicked
        // TODO add your handling code here:
        jPanel7.setVisible(true);
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
            String query="Select hotel_name,available_rooms,price_perday,extra_bed_price,number_of_adults_in_room,DESCRIPTION,city from hotel where available_rooms>0";
            PreparedStatement stat=con.prepareStatement(query);
            ResultSet res=stat.executeQuery();
            hottab.setModel(DbUtils.resultSetToTableModel(res));  
            con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class not found ");
        } catch (SQLException ex) {
              Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewallhotMouseClicked

    private void viewallhotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallhotMouseEntered
        // TODO add your handling code here:
        original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_viewallhotMouseEntered

    private void viewallhotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallhotMouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_viewallhotMouseExited

    private void viewalltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewalltaMouseClicked
        // TODO add your handling code here:
        TAtabP.setVisible(true);
        try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                String query="Select agency_name,area,city,state,phone_no from travel_agency";
                PreparedStatement stat=con.prepareStatement(query);
                ResultSet res=stat.executeQuery();
                TAtable.setModel(DbUtils.resultSetToTableModel(res));
                con.close();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class not found ");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Invalid Input");
            }
    }//GEN-LAST:event_viewalltaMouseClicked

    private void viewalltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewalltaMouseEntered
        // TODO add your handling code here:
         original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
        
    }//GEN-LAST:event_viewalltaMouseEntered

    private void viewalltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewalltaMouseExited
        // TODO add your handling code here:
        evt.getComponent().setFont(original);
    }//GEN-LAST:event_viewalltaMouseExited

    private void cancelbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbookActionPerformed
        // TODO add your handling code here:
        if(BookingTab.getSelectedRow()!=-1){
            int i=BookingTab.getSelectedRow();
            BigDecimal bid1=(BigDecimal) BookingTab.getValueAt(i,0);
            String bid=String.valueOf(bid1);
            int d=JOptionPane.showConfirmDialog(null,"Are you sure you want to cancel Booking "+bid);
            if(d==JOptionPane.YES_OPTION){
                try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","Nasil Saniah","sahil123");
                String query="delete from booking where bookingid=?";
                PreparedStatement stat=con.prepareStatement(query);
                stat.setString(1, bid);
                int res=stat.executeUpdate();
                if(res==1){
                    JOptionPane.showMessageDialog(null,"Booking "+bid+" Cancelled!");
                }
                String query2="select BOOKINGID,traveller_name,booking_date,traveller_details,hid,hotel_id,BOOKING__DETAILS from Booking where username=?";
                PreparedStatement stat2=con.prepareStatement(query2);
                stat2.setString(1,Login.n);
                ResultSet res2=stat2.executeQuery();
                BookingTab.setModel(DbUtils.resultSetToTableModel(res2));
                con.close();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class not found ");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Invalid Input");
            }
            }
        }
    }//GEN-LAST:event_cancelbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account;
    private java.awt.Button BookBtnTA;
    private java.awt.Button BookHoliday;
    private java.awt.Button BookHotelBtn;
    public static javax.swing.JTable BookingTab;
    private javax.swing.JPanel Bookings;
    private javax.swing.JLabel Changepass;
    private java.awt.Button GO;
    private java.awt.Button GOHotel;
    private javax.swing.JPanel Holidays;
    private javax.swing.JPanel Hotels;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Logout1;
    private javax.swing.JLabel Logout2;
    private javax.swing.JLabel Logout3;
    private javax.swing.JLabel Logout6;
    private javax.swing.JButton Okfeedback;
    public static javax.swing.JPanel TAspecific;
    public static javax.swing.JPanel TAtabP;
    public static javax.swing.JTable TAtable;
    private javax.swing.JPanel TravelAgencies;
    public static javax.swing.ButtonGroup bg;
    private javax.swing.ButtonGroup bg3;
    private javax.swing.JTextField bud;
    private java.awt.Button cancelbook;
    public static javax.swing.JPanel changep;
    public static javax.swing.JPanel changep1;
    private com.toedter.calendar.JDateChooser ckin;
    private com.toedter.calendar.JDateChooser ckout;
    private javax.swing.JButton confirmjButton1;
    private javax.swing.JTextField dest;
    private javax.swing.JTextArea f1;
    private javax.swing.JLabel feedback;
    private javax.swing.JTextField from;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel holiday;
    private java.awt.Button holok;
    public static javax.swing.JTable holtab;
    public static javax.swing.JTable holtab1;
    public static javax.swing.JTable hottab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel7;
    public static javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField oldpass;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JLabel packfromTA;
    private javax.swing.JButton search;
    private javax.swing.JTextField tacity;
    private javax.swing.JTextField tastate;
    private javax.swing.JLabel viewallhol;
    private javax.swing.JLabel viewallhot;
    private javax.swing.JLabel viewallta;
    private javax.swing.JLabel woeksc;
    // End of variables declaration//GEN-END:variables

    
}
